/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppButton: typeof import('./src/components/app-button/AppButton.vue')['default']
    AppDropdown: typeof import('./src/components/app-dropdown/AppDropdown.vue')['default']
    AppIcon: typeof import('./src/components/app-icon/AppIcon.vue')['default']
    AppLoading: typeof import('./src/components/app-loading/AppLoading.vue')['default']
    AppModal: typeof import('./src/components/app-modal/AppModal.vue')['default']
    AppNavbar: typeof import('./src/components/app-navbar/AppNavbar.vue')['default']
    AppSelect: typeof import('./src/components/app-select/AppSelect.vue')['default']
    AvailableTeacherCard: typeof import('./src/views/AvailableTeachers/components/available-teacher-card/AvailableTeacherCard.vue')['default']
    BackButton: typeof import('./src/components/back-button/BackButton.vue')['default']
    CharactersModal: typeof import('./src/components/characters-modal/CharactersModal.vue')['default']
    FormBackground: typeof import('./src/components/form-box/FormBackground.vue')['default']
    FormBox: typeof import('./src/components/form-box/FormBox.vue')['default']
    FormInput: typeof import('./src/components/form-input/FormInput.vue')['default']
    HeaderDashboardText: typeof import('./src/components/header-dashboard-text/header-dashboard-text.vue')['default']
    HeaderScreensText: typeof import('./src/components/header-dashboard-text/header-screens-text.vue')['default']
    Inputs: typeof import('./src/components/Inputs/Inputs.vue')['default']
    Nav_barBox: typeof import('./src/components/nav_bar-box/components/nav_bar-box.vue')['default']
    NavBar_complete: typeof import('./src/components/nav_bar-box/nav-bar_complete.vue')['default']
    ProgressBar: typeof import('./src/components/progress-bar/ProgressBar.vue')['default']
    ProjectBox: typeof import('./src/components/project-list/ProjectBox.vue')['default']
    ProjectList: typeof import('./src/components/project-list/ProjectBox.vue')['default']
    RequestCard: typeof import('./src/components/request-card/RequestCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./src/components/sidebar/Sidebar.vue')['default']
    TextButton: typeof import('./src/components/text-button/TextButton.vue')['default']
  }
}
